Docs: Setup Method Docs
ApeWorX/ape-starknet pull request #131
Opened 2023-02-10 21:59 UTC by dtdang

### What I did

fixes: #APE-55

### How I did it

### How to verify it

### Checklist

- [ ] Passes all linting checks (pre-commit and CI jobs)
- [ ] New test cases have been added and are passing
- [ ] Documentation has been updated
- [ ] PR title follows [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) standard (will be automatically included in the changelog)

2023-02-21 14:18 UTC, unparalleled-js reviewed
Nice work!

Round 2, I tried adding a bunch of feedback that may apply in more than 1 spot.

Thank you!

2023-02-21 14:18 UTC, unparalleled-js commented on ape_starknet/accounts/__init__.py
>      def genesis_test_accounts(self) -> List:
Maybe we should make this internal e.g. `_genesis_test_accounts` and then we don't need to document this / make it a public API.

2023-02-21 14:18 UTC, unparalleled-js commented on ape_starknet/accounts/__init__.py
> +            Iterator[:class:`~ape.api.AccountAPI`]
Currently, we can't link back to core. That is something to figure out later.

```suggestion
            Iterator[``AccountAPI``]
```

2023-02-21 14:18 UTC, unparalleled-js commented on ape_starknet/accounts/__init__.py
>      def load_key_file_account(self, alias: str) -> "StarknetKeyfileAccount":
Let's make this method an internal API but changing the name to `_load_key_file_account()` and removing the doc-str

2023-02-21 14:18 UTC, unparalleled-js commented on ape_starknet/accounts/__init__.py
> +            allow_local_file_store (bool): Allow for account to be stored on local file.
Add a note here.  `Defaults to True for all non-local networks and False for local networks`

2023-02-21 14:18 UTC, unparalleled-js commented on ape_starknet/accounts/__init__.py
> +            allow_local_file_store (bool): Allows to store in local file store.
Add a note here. Defaults to True for all non-local networks and False for local networks

2023-02-21 14:18 UTC, unparalleled-js commented on ape_starknet/accounts/__init__.py
> +            :class:`StarknetKeyfileAccount`
- [ ] Fix all links

2023-02-21 14:18 UTC, unparalleled-js commented on ape_starknet/accounts/__init__.py
> +                Option to leave account unlocked for future interactions. Defaults to `None`.
In doc-strs, you have to use 2 tick marks.

```suggestion
                Option to leave account unlocked for future interactions. Defaults to ``None``.
```

- [ ] Replace all single-tics with double tics in doc-strs

2023-02-21 14:18 UTC, unparalleled-js commented on ape_starknet/accounts/__init__.py
> +        Set public key of the account.
This isn't a setter

```suggestion
        The public key of the account.
```

2023-02-21 14:18 UTC, unparalleled-js commented on ape_starknet/accounts/__init__.py
> +        Encode address to int.
```suggestion
        The account's address as an integer.
```

2023-02-21 14:18 UTC, unparalleled-js commented on ape_starknet/accounts/__init__.py
> +        The contract address calcuated from
```suggestion
        The contract address if are to use default salt for the account.
```

2023-02-21 14:18 UTC, unparalleled-js commented on ape_starknet/accounts/__init__.py
> +        Write account to file.
Can we make this a non-public API as well? e.g. `_write()` ?

2023-02-21 14:18 UTC, unparalleled-js commented on ape_starknet/provider.py
> +        """Connect to client or raises a `ProviderNotConnectedError` otherwise."""
```suggestion
        """Connect to client or raises a :class:`~ape_starknet.exceptions.ProviderNotConnectedError` otherwise."""
```

2023-02-21 14:18 UTC, unparalleled-js commented on ape_starknet/provider.py
> +        """Check if client is connected to Starknet"""
```suggestion
        """An HTTP client for Starknet."""
```

2023-02-21 14:18 UTC, unparalleled-js commented on ape_starknet/provider.py
> +        """Get abi"""
```suggestion
        """Get the ABI of a contract."""
```

2023-02-21 14:18 UTC, unparalleled-js commented on ape_starknet/tokens.py
> +            token(str): The fee token name.
```suggestion
            token(str): The fee token symbol. Defaults to `ETH`.
```

2023-02-21 14:18 UTC, unparalleled-js commented on docs/methoddocs/udc.md
> +# Udc
```suggestion
# Universal Deployer
```

2023-02-21 14:18 UTC, unparalleled-js commented on docs/userguides/accounts.md
> +#### Importing an Account
The amount of `#` should only increase by 1 when moving to a sub-section.

```suggestion
## Importing an Account
```

2023-02-21 14:18 UTC, unparalleled-js commented on setup.py
> +        "eth-ape>=0.5.0,<0.7",
No, we shouldn't need to drop back to 0.5, perhaps you need to fetch core tags and re-install

```suggestion
        "eth-ape>=0.6.2,<0.7",
```

2023-02-22 03:11 UTC, dtdang commented on ape_starknet/accounts/__init__.py
> +        Write account to file.
I will make the changes to make it non-public and run the tests to make sure everything is still alright.

2023-02-22 20:42 UTC, unparalleled-js commented
@dtdang You need to rebase! That will help review the diff and also remove stuff you didn't do out of this PR.

2023-02-24 14:35 UTC, unparalleled-js requested changes
This is looking really good! Nice work managing such a large PR.

Couple big things:
* There are some docs building issues when I run `python build_docs.py`.
* The stub files needs titles or else they won't generate links
* In the build file, it says `ethpm-types` instead of `ape-starknet`
* In the conf file, it puts the link as `ape` instead of `ape-starknet`.
Those

2023-02-24 14:35 UTC, unparalleled-js commented on .github/workflows/docs.yaml
> +
Some strange whitespace down here

```suggestion

```

2023-02-24 14:35 UTC, unparalleled-js commented on README.md
> +Learn more about deploying contracts like factory contracts by following the [contracts guide](docs/userguides/contracts.md)
I am not sure this link is going to work. You may want to look at how Core is doing it.

2023-02-24 14:35 UTC, unparalleled-js commented on ape_starknet/accounts/__init__.py
> +            class_hash (int): A hash chain of the definition of the class.
`hash chain`? Is that what they really call it?

2023-02-24 14:35 UTC, unparalleled-js commented on ape_starknet/accounts/__init__.py
> +        Add deployment if network is connected to local network else, raises ``ValueError``.
There is also a `Raises:` section you can utilize:

```
Raises:
  ValueError: When connected to the local network.
```

2023-02-24 14:35 UTC, unparalleled-js commented on ape_starknet/ecosystems.py
> +            DeclareTransaction
```suggestion
            :class:`~ape_starknet.transactions.DeclareTransaction`
```

2023-02-24 14:35 UTC, unparalleled-js commented on build_docs.py
> +DOCS_BUILD_PATH = Path("docs/_build/ethpm-types")
```suggestion
DOCS_BUILD_PATH = Path("docs/_build/ape-starknet")
```

2023-02-24 14:35 UTC, unparalleled-js commented on docs/_static/custom.js
> +            // '/ape/' (return 'stable')
This comments might be misleading, not sure the correct path but I think it's `ape-starknet`.

```suggestion
            // '/ape-starknet/' (return 'stable')
```

2023-02-24 14:35 UTC, unparalleled-js commented on docs/_static/custom.js
> +});
Missing newline at the end of the file

2023-02-24 14:35 UTC, unparalleled-js commented on docs/conf.py
> +html_baseurl = "/ape/"
```suggestion
html_baseurl = "/ape-starknet/"
```

2023-02-24 14:35 UTC, unparalleled-js commented on docs/userguides/contracts.md
> +# Contracts
I feel like we need a normal section about contracts too, like basic contract interaction. It could even just link to the normal Ape docs for that.

2023-02-24 15:22 UTC, dtdang commented on README.md
> +Learn more about deploying contracts like factory contracts by following the [contracts guide](docs/userguides/contracts.md)
We have both the full link as well as this link in the Core docs but I can change it to the full link. I just didn't know if the full link would work while testing with the local server.

2023-02-24 15:28 UTC, dtdang commented on ape_starknet/accounts/__init__.py
> +            class_hash (int): A hash chain of the definition of the class.
That's what Starknet has in their docs for class hash

2023-02-24 16:04 UTC, unparalleled-js commented on README.md
> +Learn more about deploying contracts like factory contracts by following the [contracts guide](docs/userguides/contracts.md)
And, ya it might not work the greatest for the local server but it's better than 404

2023-02-27 02:00 UTC, dtdang commented on README.md
> +Learn more about deploying contracts like factory contracts by following the [contracts guide](docs/userguides/contracts.md)
Part of the links 404 on the core docs site are from typos that I'm fixing with my bug pr there but I'm putting full links in for now even if they won't work before we deploy on github pages.

2023-02-27 02:11 UTC, dtdang commented
Started getting an issue about `Unable to parse ContractType from 'traces-testnet-block-243810.json'.` so I'm going to go through and figure out where that came from since we changed a few functions.

2023-02-27 02:27 UTC, unparalleled-js commented
> Started getting an issue about `Unable to parse ContractType from 'traces-testnet-block-243810.json'.` so I'm going to go through and figure out where that came from since we changed a few functions.

That feels doesn't seem like ours.
Perhaps `starknet-devnet` (or something) is putting JSON files in our `contracts/` folder` and causing `CompilerError`s.
We need to ignore these files somehow; they shouldn't compile by Ape..

I am suspicious that Ape may be using the wrong `contracts/` folder in the tests.

2023-02-27 17:55 UTC, unparalleled-js commented
Looks like tests are failing because of some of the renames we did here.
Also don't forgot to run all the linters and code formatters! That will clear those up.

2023-02-27 17:56 UTC, unparalleled-js reviewed
After addressing `python build_docs.py` should look nicer and the site should build more correctly

2023-02-27 17:56 UTC, unparalleled-js commented on docs/conf.py
> +    build_dir = Path(__file__).parent / "_build" / "ape"
```suggestion
    build_dir = Path(__file__).parent / "_build" / "ape-starknet"
```

2023-02-27 17:56 UTC, unparalleled-js commented on docs/commands/accounts.rst
> +.. click:: ape_starknet._cli:cli
Change this whole file to:

```
accounts
********

.. click:: ape_starknet.accounts._cli:accounts
  :prog: accounts
  :nested: full

```

* Fixes the path
* Not sure why, but this needs a manually set title to work.. Really not sure why

But put those two things together, and this finally shows up in the docs without build errors.

2023-02-27 17:56 UTC, unparalleled-js commented on docs/userguides/contracts.md
> +```cairo
Remove `cairo` after the three tick marks here to fix the `build_docs.py` warning `WARNING: Pygments lexer name 'cairo' is not known` that appears.

2023-02-28 15:40 UTC, unparalleled-js approved these changes

2023-02-28 15:52 UTC, merged